/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganicoRouteImport } from './routes/organico'
import { Route as IndexRouteImport } from './routes/index'

const OrganicoRoute = OrganicoRouteImport.update({
  id: '/organico',
  path: '/organico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organico': typeof OrganicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organico': typeof OrganicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organico': typeof OrganicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/organico'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/organico'
  id: '__root__' | '/' | '/organico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganicoRoute: typeof OrganicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organico': {
      id: '/organico'
      path: '/organico'
      fullPath: '/organico'
      preLoaderRoute: typeof OrganicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganicoRoute: OrganicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
